In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\Mahendra Wagh\Documents\Data set\credit card fraud.zip")

In [3]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [4]:
df.duplicated().sum()

1081

In [5]:
df.drop(["Time","Amount"],axis=1,inplace=True)

In [6]:
df.head()

V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10  ...       V20       V21       V22       V23  \
0  0.098698  0.363787  0.090794  ...  0.251412 -0.018307  0.277838 -0.110474   
1  0.085102 -0.255425 -0.166974  ... -0.069083 -0.225775 -0.638672  0.101288   
2  0.247676 -1.514654  0.207643  ...  0.524980  0.247998  0.771679  0.909412   
3  0.377436 -1.387024 -0.054952  ... -0.208038 -0.108300  0.005274 -0.190321   
4 -0.270533  0.817739  0.753074  ...  0.408542 -0.009431  0.798278 -0.137458   

        V24       V25       V26       V27       V28  Class  
0  0.066928  0.128539 -0.189115  0.133558 -0.021053      0  
1 -0.339846  0.167170  0.125895 -0.008983  0.014724      0  
2 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752      0  
3 -1.175575  0.647376 -0.221929  0.062723  0.061458      0  
4  0.141267 -0.206010  0.502292  0.219422  0.215153      0  

[5 rows x 29 columns]

In [7]:
df.shape

(284807, 29)

In [8]:
print(df.isna().sum())

V1       0
V2       0
V3       0
V4       0
V5       0
V6       0
V7       0
V8       0
V9       0
V10      0
V11      0
V12      0
V13      0
V14      0
V15      0
V16      0
V17      0
V18      0
V19      0
V20      0
V21      0
V22      0
V23      0
V24      0
V25      0
V26      0
V27      0
V28      0
Class    0
dtype: int64


In [9]:
df.loc[(df['Class']==1)]

V1        V2        V3        V4        V5        V6        V7  \
541    -2.312227  1.951992 -1.609851  3.997906 -0.522188 -1.426545 -2.537387   
623    -3.043541 -3.157307  1.088463  2.288644  1.359805 -1.064823  0.325574   
4920   -2.303350  1.759247 -0.359745  2.330243 -0.821628 -0.075788  0.562320   
6108   -4.397974  1.358367 -2.592844  2.679787 -1.128131 -1.706536 -3.496197   
6329    1.234235  3.019740 -4.304597  4.732795  3.624201 -1.357746  1.713445   
...          ...       ...       ...       ...       ...       ...       ...   
279863 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494 -0.882850   
280143  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536 -1.413170   
280149 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346 -2.234739   
281144 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548 -2.208002   
281674  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695  0.223050   

              V8        V9       V10  ...       V20       V21       V22  \
541     1.391657 -2.770089 -2.772272  ...  0.126911  0.517232 -0.035049   
623    -0.067794 -0.270953 -0.838587  ...  2.102339  0.661696  0.435477   
4920   -0.399147 -0.238253 -1.525412  ... -0.430022 -0.294166 -0.932391   
6108   -0.248778 -0.247768 -4.801637  ... -0.171608  0.573574  0.176968   
6329   -0.496358 -1.282858 -2.447469  ...  0.009061 -0.379068 -0.704181   
...          ...       ...       ...  ...       ...       ...       ...   
279863  0.697211 -2.064945 -5.587794  ...  1.252967  0.778584 -0.319189   
280143  0.248525 -1.127396 -3.232153  ...  0.226138  0.370612  0.028234   
280149  1.210158 -0.652250 -3.463891  ...  0.247968  0.751826  0.834108   
281144  1.058733 -1.632333 -5.245984  ...  0.306271  0.583276 -0.269209   
281674 -0.068384  0.577829 -0.888722  ... -0.017652 -0.164350 -0.295135   

             V23       V24       V25       V26       V27       V28  Class  
541    -0.465211  0.320198  0.044519  0.177840  0.261145 -0.143276      1  
623     1.375966 -0.293803  0.279798 -0.145362 -0.252773  0.035764      1  
4920    0.172726 -0.087330 -0.156114 -0.542628  0.039566 -0.153029      1  
6108   -0.436207 -0.053502  0.252405 -0.657488 -0.827136  0.849573      1  
6329   -0.656805 -1.632653  1.488901  0.566797 -0.010016  0.146793      1  
...          ...       ...       ...       ...       ...       ...    ...  
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968      1  
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637      1  
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361      1  
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700      1  
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309      1  

[492 rows x 29 columns]

In [10]:
import sklearn
from sklearn.model_selection import train_test_split

In [11]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [12]:
#taking random state =100

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=100)

In [14]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [15]:
y_pred=model.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [59]:
print("Train Accuracy:", model.score(x_train,y_train))
print("Test Accuracy:", model.score(x_test,y_test))


Train Accuracy: 0.9444652872873248
Test Accuracy: 0.9434924520603836


In [58]:
# model get biased 

In [16]:
df.tail()

V1         V2        V3        V4        V5        V6  \
284802 -11.881118  10.071785 -9.834783 -2.066656 -5.364473 -2.606837   
284803  -0.732789  -0.055080  2.035030 -0.738589  0.868229  1.058415   
284804   1.919565  -0.301254 -3.249640 -0.557828  2.630515  3.031260   
284805  -0.240440   0.530483  0.702510  0.689799 -0.377961  0.623708   
284806  -0.533413  -0.189733  0.703337 -0.506271 -0.012546 -0.649617   

              V7        V8        V9       V10  ...       V20       V21  \
284802 -4.918215  7.305334  1.914428  4.356170  ...  1.475829  0.213454   
284803  0.024330  0.294869  0.584800 -0.975926  ...  0.059616  0.214205   
284804 -0.296827  0.708417  0.432454 -0.484782  ...  0.001396  0.232045   
284805 -0.686180  0.679145  0.392087 -0.399126  ...  0.127434  0.265245   
284806  1.577006 -0.414650  0.486180 -0.915427  ...  0.382948  0.261057   

             V22       V23       V24       V25       V26       V27       V28  \
284802  0.111864  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731   
284803  0.924384  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   
284804  0.578229 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   
284805  0.800049 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   
284806  0.643078  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649   

        Class  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[5 rows x 29 columns]

In [17]:
sample_data1=df.iloc[:5,:-1]
sample_data2=df.iloc[284802:,:-1]
sample_data3=df.iloc[[541,623,4920],:-1]
sample_data4=df.iloc[[2,3,5,541,623,4920,284806],:-1]

In [18]:
y_pred=model.predict(sample_data1)
y_pred

C:\Users\Mahendra Wagh\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


array([0, 0, 0, 0, 0], dtype=int64)

In [ ]:
# model get biased  to the farud not found.

In [19]:
y_pred=model.predict(sample_data2)
y_pred

C:\Users\Mahendra Wagh\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


array([0, 0, 0, 0, 0], dtype=int64)

In [20]:
y_pred=model.predict(sample_data3)
y_pred

C:\Users\Mahendra Wagh\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


array([0, 0, 0], dtype=int64)

In [21]:
_pred=model.predict(sample_data4)
y_pred

C:\Users\Mahendra Wagh\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


array([0, 0, 0], dtype=int64)

In [ ]:
# model get biased  to the farud not found.

In [24]:
df.Class.value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [ ]:
# model imbalancing technique

### Random Over Sampling


In [25]:
import imblearn
from imblearn.over_sampling import RandomOverSampler
from collections import Counter

In [26]:
ros = RandomOverSampler(random_state=0)
x_resample, y_resample = ros.fit_resample(x, y)
print((Counter(y_resample)))

Counter({0: 284315, 1: 284315})


In [27]:
Counter(x_resample.shape)

Counter({568630: 1, 28: 1})

In [28]:
Counter(y_resample)

Counter({0: 284315, 1: 284315})

In [29]:
x_train,x_test,y_train,y_test=train_test_split(x_resample,y_resample,test_size=0.2,random_state=110)

In [30]:
Counter(y_train)

Counter({0: 227623, 1: 227281})

In [31]:
Counter(y_test)

Counter({1: 57034, 0: 56692})

In [32]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [33]:
y_sample_pred=model.predict(x_test)
y_sample_pred

array([0, 0, 0, ..., 1, 1, 0], dtype=int64)

In [34]:
x_resample

array([[-1.35980713, -0.07278117,  2.53634674, ..., -0.18911484,
         0.13355838, -0.02105305],
       [ 1.19185711,  0.26615071,  0.16648011, ...,  0.12589453,
        -0.0089831 ,  0.01472417],
       [-1.35835406, -1.34016307,  1.77320934, ..., -0.13909657,
        -0.05535279, -0.05975184],
       ...,
       [-2.86979495,  1.33566696, -1.0095302 , ..., -0.45365101,
         0.34919104,  0.19886227],
       [-2.78724793, -0.07134038, -1.50528778, ..., -0.26589432,
         0.22069402,  0.25607687],
       [-3.36531852,  2.42650326, -3.75222653, ..., -1.05599733,
        -1.20016497, -1.01206584]])

In [35]:
#test size=0.3
# random state=500
x_train,x_test,y_train,y_test=train_test_split(x_resample,y_resample,test_size=0.3,random_state=500)

In [36]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [37]:
y_sample_pred=model.predict(x_test)
y_sample_pred

array([1, 0, 1, ..., 0, 0, 1], dtype=int64)

In [38]:
sample_data4=df.iloc[[2,3,5,541,623,4920,284806],:-1]
y_pred=model.predict(sample_data4)
y_pred

C:\Users\Mahendra Wagh\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


array([0, 0, 0, 1, 1, 1, 0], dtype=int64)

In [57]:
print("Train Accuracy:", model.score(x_train,y_train))
print("Test Accuracy:", model.score(x_test,y_test))


Train Accuracy: 0.9444652872873248
Test Accuracy: 0.9434924520603836


## Random Under Sampling

In [39]:
from imblearn.under_sampling import RandomUnderSampler

In [40]:
rrs = RandomUnderSampler(random_state=0)
x_resample, y_resample = rrs.fit_resample(x, y)
print((Counter(y_resample)))

Counter({0: 492, 1: 492})


In [41]:
x_train,x_test,y_train,y_test=train_test_split(x_resample,y_resample,test_size=0.25,random_state=100)

In [42]:
Counter(y_train)

Counter({1: 380, 0: 358})

In [43]:
Counter(y_test)

Counter({1: 112, 0: 134})

In [44]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [45]:
y_pred=model.predict(sample_data4)
y_pred

C:\Users\Mahendra Wagh\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


array([0, 0, 0, 1, 1, 1, 0], dtype=int64)

In [56]:
print("Train Accuracy:", model.score(x_train,y_train))
print("Test Accuracy:", model.score(x_test,y_test))


Train Accuracy: 0.9444652872873248
Test Accuracy: 0.9434924520603836


In [46]:
df.head()

V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10  ...       V20       V21       V22       V23  \
0  0.098698  0.363787  0.090794  ...  0.251412 -0.018307  0.277838 -0.110474   
1  0.085102 -0.255425 -0.166974  ... -0.069083 -0.225775 -0.638672  0.101288   
2  0.247676 -1.514654  0.207643  ...  0.524980  0.247998  0.771679  0.909412   
3  0.377436 -1.387024 -0.054952  ... -0.208038 -0.108300  0.005274 -0.190321   
4 -0.270533  0.817739  0.753074  ...  0.408542 -0.009431  0.798278 -0.137458   

        V24       V25       V26       V27       V28  Class  
0  0.066928  0.128539 -0.189115  0.133558 -0.021053      0  
1 -0.339846  0.167170  0.125895 -0.008983  0.014724      0  
2 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752      0  
3 -1.175575  0.647376 -0.221929  0.062723  0.061458      0  
4  0.141267 -0.206010  0.502292  0.219422  0.215153      0  

[5 rows x 29 columns]

# SMOTE 

In [47]:
from imblearn.over_sampling import SMOTE
s=SMOTE()
x2_df,y2_df=s.fit_resample(x,y)

In [48]:
rsms = SMOTE(random_state=0)
x_resample, y_resample = rsms.fit_resample(x, y)
print((Counter(y_resample)))

Counter({0: 284315, 1: 284315})


In [49]:
Counter(y_train)

Counter({1: 380, 0: 358})

In [50]:
Counter(y_test)

Counter({1: 112, 0: 134})

In [51]:
x_train,x_test,y_train,y_test=train_test_split(x_resample,y_resample,test_size=0.25,random_state=100)

In [52]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [53]:
y_pred=model.predict(sample_data4)
y_pred

C:\Users\Mahendra Wagh\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


array([0, 0, 0, 1, 1, 1, 0], dtype=int64)

In [55]:
print("Train Accuracy:", model.score(x_train,y_train))
print("Test Accuracy:", model.score(x_test,y_test))


Train Accuracy: 0.9444652872873248
Test Accuracy: 0.9434924520603836
